# PyTorch for Beginners

In this notebook, we will try out the codes we used in the [PyTorch for Beginners](https://www.learnopencv.com/pytorch-for-beginners-basics/) blog.

Let's start off by installing PyTorch.

In [7]:
# Use this if you have conda installed
# !conda install -c pytorch pytorch

# Use this if you are on Google Colab
# or don't have conda installed
!pip3 install torch

Let's verify that we have the latest PyTorch version (1.1.0)

In [0]:
import torch

In [9]:
print("torch version : {}".format(torch.__version__))

torch version : 1.1.0


# Introduction to Tensors

## Construct your first Tensor

Let’s see how we can create a PyTorch Tensor. 

In [11]:
# Create a Tensor with just ones in a column
a = torch.ones(5)
# Print the tensor we created
print(a)
 
# Create a Tensor with just zeros in a column
b = torch.zeros(5)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


We can similarly create Tensor with custom values as shown below.

In [12]:
c = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
print(c)

tensor([1., 2., 3., 4., 5.])


In all the above cases, we have created vectors or Tensors of dimension 1. Now, let’s create some tensors of higher dimension.

In [15]:
d = torch.zeros(3,2)
print(d)

e = torch.ones(3,2)
print(e)

f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(f)

# 3D Tensor
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


We can also find out the shape of a Tensor using **`.shape`** method.

In [16]:
print(f.shape)
 
print(e.shape)
 
print(g.shape)

torch.Size([2, 2])
torch.Size([3, 2])
torch.Size([2, 2, 2])


## Access an element in Tensor

Now that we have created some tensors, let’s see how we can access an element in a Tensor. First let’s see how to do this for 1D Tensor aka vector.

In [17]:
# Get element at index 2
print(c[2])

tensor(3.)


What about 2D or 3D Tensor? Recall what we mentioned about **dimension of a tensor**. 

To access one particular element in a tensor, we will need to specify indices equal to the dimension of the tensor. That’s why for tensor **`c`** we only had to specify one index.

In [18]:
# All indices starting from 0
 
# Get element at row 1, column 0
print(f[1,0])

# We can also use the following
print(f[1][0])

# Similarly for 3D Tensor
print(g[1,0,0])
print(g[1][0][0])

tensor(3.)
tensor(3.)
tensor(5.)
tensor(5.)


But what if you wanted to access one entire row in a 2D Tensor?

In [19]:
# All elements
print(f[:])
 
# All elements from index 1 to 2 (inclusive)
print(c[1:3])
 
# All elements till index 4 (exclusive)
print(c[:4])
 
# First row
print(f[0,:])
 
# Second column
print(f[:,1])

tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])
tensor([1., 2., 3., 4.])
tensor([1., 2.])
tensor([2., 4.])


## Specify data type of elements

Whenever we create a tensor, PyTorch decides the data type of the elements of the tensor such that the data type can cover all the elements of the tensor. We can override this by specifying the data type while creating the tensor.

In [20]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)
 
# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)
print(int_tensor)
 
 
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)
print(int_tensor)

torch.int64
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## Tensor to/from NumPy Array

We have mentioned several times that PyTorch Tensors and NumPy arrays are pretty similar. This of course demands the question if it’s possible to convert one data structure into another. Let’s see how we can do this.

In [21]:
# Import NumPy
import numpy as np
 
# Tensor to Array
f_numpy = f.numpy()
print(f_numpy)
 
# Array to Tensor
h = np.array([[8,7,6,5],[4,3,2,1]])
h_tensor = torch.from_numpy(h)
print(h_tensor)

[[1. 2.]
 [3. 4.]]
tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


## Arithmetic Operations on Tensors

Now it’s time for the next step. Let’s see how we can perform arithmetic operations on PyTorch tensors.

In [23]:
# Create tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])
 
# Addition
print(tensor1+tensor2)
# We can also use
print(torch.add(tensor1,tensor2))
 
# Subtraction
print(tensor1-tensor2)
# We can also use
print(torch.sub(tensor1,tensor2))
 
# Multiplication
# Tensor with Scalar
print(tensor1 * 2)
 
# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)
 
# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))
 
# Division
# Tensor with scalar
print(tensor1/2)
 
# Tensor with another tensor
# Elementwise division
print(tensor1/tensor2)

tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ -1,   4,  -9],
        [ 16, -25,  36]])
tensor([[22, 28],
        [49, 64]])
tensor([[0, 1, 1],
        [2, 2, 3]])
tensor([[-1,  1, -1],
        [ 1, -1,  1]])


## CPU v/s GPU Tensor

Let’s first see how to create a tensor for GPU.

In [0]:
# Create a tensor for CPU
# This will occupy CPU RAM
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')
 
# Create a tensor for GPU
# This will occupy GPU RAM
tensor_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cuda')

Just like tensor creation, the operations performed for CPU and GPU tensors are also different and consume RAM corresponding to the device specified.

In [0]:
# This uses CPU RAM
tensor_cpu = tensor_cpu * 5
 
# This uses GPU RAM
# Focus on GPU RAM Consumption
tensor_gpu = tensor_gpu * 5

We can move the GPU tensor to CPU and vice versa as shown below.

In [0]:
# Move GPU tensor to CPU
tensor_gpu_cpu = tensor_gpu.to(device='cpu')
 
# Move CPU tensor to GPU
tensor_cpu_gpu = tensor_cpu.to(device='cuda')

## Thank You!

That's all folks for now. Hope you enjoyed the blog.